version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
     - ./backend:/usr/src/app
     - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - uctenka_db:/var/lib/postgresql/data
